#############################################################################
# Makefile for building: Bricked-Installer
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Jul 2 18:37:34 2012
# Project:  Bricked-Installer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Bricked-Installer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"0.1\" -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		dragons.cpp \
		info.cpp \
		detect.cpp \
		flasher.cpp \
		openfile.cpp \
		quazip/unzip.c \
		quazip/zip.c \
		quazip/JlCompress.cpp \
		quazip/qioapi.cpp \
		quazip/quaadler32.cpp \
		quazip/quacrc32.cpp \
		quazip/quazip.cpp \
		quazip/quazipfile.cpp \
		quazip/quazipnewinfo.cpp moc_mainwindow.cpp \
		moc_dragons.cpp \
		moc_info.cpp \
		moc_detect.cpp \
		moc_flasher.cpp \
		moc_openfile.cpp \
		moc_quazipfile.cpp \
		qrc_res_loc.cpp
OBJECTS       = main.o \
		mainwindow.o \
		dragons.o \
		info.o \
		detect.o \
		flasher.o \
		openfile.o \
		unzip.o \
		zip.o \
		JlCompress.o \
		qioapi.o \
		quaadler32.o \
		quacrc32.o \
		quazip.o \
		quazipfile.o \
		quazipnewinfo.o \
		moc_mainwindow.o \
		moc_dragons.o \
		moc_info.o \
		moc_detect.o \
		moc_flasher.o \
		moc_openfile.o \
		moc_quazipfile.o \
		qrc_res_loc.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Bricked-Installer.pro
QMAKE_TARGET  = Bricked-Installer
DESTDIR       = 
TARGET        = Bricked-Installer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_dragons.h ui_info.h ui_detect.h ui_flasher.h ui_openfile.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bricked-Installer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Bricked-Installer.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile Bricked-Installer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Bricked-Installer0.1 || $(MKDIR) .tmp/Bricked-Installer0.1 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Bricked-Installer0.1/ && $(COPY_FILE) --parents mainwindow.h dragons.h info.h detect.h flasher.h openfile.h quazip/crypt.h quazip/ioapi.h quazip/JlCompress.h quazip/quaadler32.h quazip/quachecksum32.h quazip/quacrc32.h quazip/quazipfile.h quazip/quazipfileinfo.h quazip/quazip_global.h quazip/quazip.h quazip/quazipnewinfo.h quazip/unzip.h quazip/zip.h .tmp/Bricked-Installer0.1/ && $(COPY_FILE) --parents res/res_loc.qrc .tmp/Bricked-Installer0.1/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp dragons.cpp info.cpp detect.cpp flasher.cpp openfile.cpp quazip/unzip.c quazip/zip.c quazip/JlCompress.cpp quazip/qioapi.cpp quazip/quaadler32.cpp quazip/quacrc32.cpp quazip/quazip.cpp quazip/quazipfile.cpp quazip/quazipnewinfo.cpp .tmp/Bricked-Installer0.1/ && $(COPY_FILE) --parents mainwindow.ui dragons.ui info.ui detect.ui flasher.ui openfile.ui .tmp/Bricked-Installer0.1/ && (cd `dirname .tmp/Bricked-Installer0.1` && $(TAR) Bricked-Installer0.1.tar Bricked-Installer0.1 && $(COMPRESS) Bricked-Installer0.1.tar) && $(MOVE) `dirname .tmp/Bricked-Installer0.1`/Bricked-Installer0.1.tar.gz . && $(DEL_FILE) -r .tmp/Bricked-Installer0.1


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_dragons.cpp moc_info.cpp moc_detect.cpp moc_flasher.cpp moc_openfile.cpp moc_quazipfile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_dragons.cpp moc_info.cpp moc_detect.cpp moc_flasher.cpp moc_openfile.cpp moc_quazipfile.cpp
moc_mainwindow.cpp: info.h \
		detect.h \
		openfile.h \
		flasher.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_dragons.cpp: mainwindow.h \
		info.h \
		detect.h \
		openfile.h \
		flasher.h \
		dragons.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dragons.h -o moc_dragons.cpp

moc_info.cpp: info.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) info.h -o moc_info.cpp

moc_detect.cpp: info.h \
		openfile.h \
		flasher.h \
		detect.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) detect.h -o moc_detect.cpp

moc_flasher.cpp: info.h \
		flasher.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) flasher.h -o moc_flasher.cpp

moc_openfile.cpp: info.h \
		flasher.h \
		openfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) openfile.h -o moc_openfile.cpp

moc_quazipfile.cpp: quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h \
		quazip/quazipfile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) quazip/quazipfile.h -o moc_quazipfile.cpp

compiler_rcc_make_all: qrc_res_loc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res_loc.cpp
qrc_res_loc.cpp: res/res_loc.qrc \
		res/img_us/skyscraper.png
	/usr/bin/rcc -name res_loc res/res_loc.qrc -o qrc_res_loc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_dragons.h ui_info.h ui_detect.h ui_flasher.h ui_openfile.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_dragons.h ui_info.h ui_detect.h ui_flasher.h ui_openfile.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_dragons.h: dragons.ui
	/usr/bin/uic-qt4 dragons.ui -o ui_dragons.h

ui_info.h: info.ui
	/usr/bin/uic-qt4 info.ui -o ui_info.h

ui_detect.h: detect.ui
	/usr/bin/uic-qt4 detect.ui -o ui_detect.h

ui_flasher.h: flasher.ui
	/usr/bin/uic-qt4 flasher.ui -o ui_flasher.h

ui_openfile.h: openfile.ui
	/usr/bin/uic-qt4 openfile.ui -o ui_openfile.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dragons.h \
		mainwindow.h \
		info.h \
		detect.h \
		openfile.h \
		flasher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		info.h \
		detect.h \
		openfile.h \
		flasher.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

dragons.o: dragons.cpp dragons.h \
		mainwindow.h \
		info.h \
		detect.h \
		openfile.h \
		flasher.h \
		ui_dragons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dragons.o dragons.cpp

info.o: info.cpp info.h \
		ui_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o info.o info.cpp

detect.o: detect.cpp detect.h \
		info.h \
		openfile.h \
		flasher.h \
		ui_detect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detect.o detect.cpp

flasher.o: flasher.cpp flasher.h \
		info.h \
		ui_flasher.h \
		openfile.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h \
		quazip/JlCompress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flasher.o flasher.cpp

openfile.o: openfile.cpp openfile.h \
		info.h \
		flasher.h \
		ui_openfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openfile.o openfile.cpp

unzip.o: quazip/unzip.c quazip/unzip.h \
		quazip/ioapi.h \
		quazip/crypt.h \
		quazip/quazip_global.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o unzip.o quazip/unzip.c

zip.o: quazip/zip.c quazip/zip.h \
		quazip/ioapi.h \
		quazip/quazip_global.h \
		quazip/crypt.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zip.o quazip/zip.c

JlCompress.o: quazip/JlCompress.cpp quazip/JlCompress.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h \
		quazip/quazipfile.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JlCompress.o quazip/JlCompress.cpp

qioapi.o: quazip/qioapi.cpp quazip/ioapi.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qioapi.o quazip/qioapi.cpp

quaadler32.o: quazip/quaadler32.cpp quazip/quaadler32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quaadler32.o quazip/quaadler32.cpp

quacrc32.o: quazip/quacrc32.cpp quazip/quacrc32.h \
		quazip/quachecksum32.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quacrc32.o quazip/quacrc32.cpp

quazip.o: quazip/quazip.cpp quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazip_global.h \
		quazip/quazipfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazip.o quazip/quazip.cpp

quazipfile.o: quazip/quazipfile.cpp quazip/quazipfile.h \
		quazip/quazip_global.h \
		quazip/quazip.h \
		quazip/zip.h \
		quazip/ioapi.h \
		quazip/unzip.h \
		quazip/quazipfileinfo.h \
		quazip/quazipnewinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipfile.o quazip/quazipfile.cpp

quazipnewinfo.o: quazip/quazipnewinfo.cpp quazip/quazipnewinfo.h \
		quazip/quazip_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quazipnewinfo.o quazip/quazipnewinfo.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dragons.o: moc_dragons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dragons.o moc_dragons.cpp

moc_info.o: moc_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_info.o moc_info.cpp

moc_detect.o: moc_detect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detect.o moc_detect.cpp

moc_flasher.o: moc_flasher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_flasher.o moc_flasher.cpp

moc_openfile.o: moc_openfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openfile.o moc_openfile.cpp

moc_quazipfile.o: moc_quazipfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quazipfile.o moc_quazipfile.cpp

qrc_res_loc.o: qrc_res_loc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res_loc.o qrc_res_loc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

